// ═══════════════════════════════════════════════════════════════
// Cinematic 3D Scroll Builder — Pre-configured Templates
// ═══════════════════════════════════════════════════════════════

import type { TemplateConfig } from './types';

export const CINEMATIC_TEMPLATES: TemplateConfig[] = [
  {
    id: 'saas-dark',
    name: 'SaaS Dark Premium',
    description: 'Landing page SaaS haut de gamme avec fond cinématique sombre, typographie bold et CTA lumineux',
    category: 'SaaS',
    color: '#6366f1',
    imagePromptSuffix: 'dark futuristic tech environment, deep blue and purple tones, volumetric lighting, abstract data visualization, premium software aesthetic',
    videoPromptSuffix: 'Slow cinematic camera push through dark tech environment, subtle particle effects, volumetric light rays, smooth dolly movement',
    siteStyle: {
      fontFamily: "'Inter', sans-serif",
      bgColor: '#0a0a0f',
      textColor: '#f0f0f5',
      accentColor: '#6366f1',
      overlayOpacity: 0.7,
      sectionCount: 5,
      heroTitle: 'The Future of Work',
      heroSubtitle: 'Powerful tools for modern teams',
    },
    defaultFps: 24,
  },
  {
    id: 'portfolio-minimal',
    name: 'Portfolio Créatif Minimaliste',
    description: 'Portfolio artiste avec scroll immersif, espaces blancs généreux et typographie raffinée',
    category: 'Portfolio',
    color: '#f59e0b',
    imagePromptSuffix: 'minimalist creative studio, soft natural lighting, muted earth tones, beautiful composition with negative space, artistic and elegant',
    videoPromptSuffix: 'Gentle cinematic pan across minimalist space, soft focus transitions, warm ambient light, smooth slow motion',
    siteStyle: {
      fontFamily: "'Playfair Display', serif",
      bgColor: '#fafaf8',
      textColor: '#1a1a1a',
      accentColor: '#d97706',
      overlayOpacity: 0.3,
      sectionCount: 4,
      heroTitle: 'Creative Vision',
      heroSubtitle: 'Design · Photography · Art Direction',
    },
    defaultFps: 24,
  },
  {
    id: 'ecommerce-luxe',
    name: 'E-commerce Luxe',
    description: 'Boutique de luxe avec effet de défilement produit, dorures et animations premium',
    category: 'E-commerce',
    color: '#d4af37',
    imagePromptSuffix: 'luxury product showcase, black marble surface, golden accents, dramatic studio lighting, premium brand aesthetic, glossy reflections',
    videoPromptSuffix: 'Slow orbit around luxury product, dramatic lighting reveals, golden highlights appearing, smooth 360 movement',
    siteStyle: {
      fontFamily: "'Cormorant Garamond', serif",
      bgColor: '#0d0d0d',
      textColor: '#e8e0d0',
      accentColor: '#d4af37',
      overlayOpacity: 0.6,
      sectionCount: 5,
      heroTitle: 'Timeless Elegance',
      heroSubtitle: 'Crafted with precision',
    },
    defaultFps: 30,
  },
  {
    id: 'startup-ai',
    name: 'Startup AI Futuriste',
    description: 'Landing page startup IA avec dégradés néon, grilles holographiques et animations de données',
    category: 'Startup',
    color: '#06b6d4',
    imagePromptSuffix: 'futuristic AI visualization, neon cyan and magenta gradients, holographic grid, neural network patterns, digital brain, cyber aesthetic',
    videoPromptSuffix: 'Dynamic camera fly-through of digital neural landscape, pulsing neon connections, holographic data streams, fast-forward time-lapse feel',
    siteStyle: {
      fontFamily: "'Space Grotesk', sans-serif",
      bgColor: '#030712',
      textColor: '#e0f2fe',
      accentColor: '#06b6d4',
      overlayOpacity: 0.65,
      sectionCount: 6,
      heroTitle: 'Intelligence Amplified',
      heroSubtitle: 'AI that understands your business',
    },
    defaultFps: 24,
  },
  {
    id: 'agency-brutale',
    name: 'Agence Créative Brutale',
    description: 'Site agence avec typographie massive, contrastes forts et vidéo full-bleed',
    category: 'Agency',
    color: '#ef4444',
    imagePromptSuffix: 'bold brutalist architecture, high contrast black and white with red accents, raw concrete textures, strong geometric shapes, industrial aesthetic',
    videoPromptSuffix: 'Dramatic crane shot revealing brutalist architecture, harsh shadows moving, high contrast transitions, powerful camera movements',
    siteStyle: {
      fontFamily: "'Bebas Neue', sans-serif",
      bgColor: '#111111',
      textColor: '#ffffff',
      accentColor: '#ef4444',
      overlayOpacity: 0.5,
      sectionCount: 4,
      heroTitle: 'WE CREATE BOLD.',
      heroSubtitle: 'Digital agency for brands that dare',
    },
    defaultFps: 30,
  },
  {
    id: 'app-mobile',
    name: 'App Mobile Moderne',
    description: 'Présentation app mobile avec mockups flottants, dégradés doux et scroll parallaxe multicouche',
    category: 'Mobile App',
    color: '#8b5cf6',
    imagePromptSuffix: 'modern mobile app interface floating in space, soft gradient background purple to blue, clean UI mockup, beautiful depth of field, glass morphism',
    videoPromptSuffix: 'Gentle parallax layers of floating UI elements, soft depth transitions, app screens gliding smoothly, dreamy atmosphere',
    siteStyle: {
      fontFamily: "'DM Sans', sans-serif",
      bgColor: '#0f0720',
      textColor: '#f3f0ff',
      accentColor: '#8b5cf6',
      overlayOpacity: 0.55,
      sectionCount: 5,
      heroTitle: 'Your App, Reimagined',
      heroSubtitle: 'Beautiful. Fast. Intuitive.',
    },
    defaultFps: 24,
  },
];
