#!/usr/bin/env node
/**
 * compile-skills.js — Pre-compile top skill files into a TypeScript map
 * for Edge runtime (can't use fs at runtime). Run at build time.
 * 
 * Usage: node scripts/compile-skills.js
 * Output: lib/compiled-skills.ts
 */

const fs = require('fs');
const path = require('path');

const SKILLS_DIR = path.join(__dirname, '..', '.agents', 'skills');
const OUTPUT_FILE = path.join(__dirname, '..', 'lib', 'compiled-skills.ts');

// Domain → skill directory names (in priority order)
const DOMAIN_SKILL_MAP = {
  'react': ['react-best-practices', 'react', 'react-components', 'react-state-management'],
  'nextjs': ['nextjs-app-router-patterns', 'nextjs'],
  'ui-design': ['tailwind-design-system', 'tailwind-best-practices', 'responsive-design'],
  'animation': ['gsap-animation', 'framer-motion'],
  'accessibility': ['accessibility', 'accessibility-aria-expert'],
  'api': ['api-design-principles'],
  'database': ['database-query', 'database-migration'],
  'auth': ['auth-implementation-patterns', 'auth'],
  'payments': ['stripe-integration', 'stripe-best-practices'],
  'testing': ['testing'],
  'performance': ['web-perf', 'performance'],
  'deploy': ['deploy-to-vercel', 'deploy-checklist', 'deploy'],
  'seo': ['seo'],
  'landing': ['landing-page-design'],
  'ecommerce': ['stripe-integration', 'database-migration'],
  'saas': ['auth-implementation-patterns', 'stripe-integration', 'database-migration'],
  'portfolio': ['landing-page-design', 'responsive-design'],
};

// Budget: max 4000 chars per skill file to keep total manageable
const MAX_CHARS_PER_SKILL = 4000;

function loadSkill(skillDir) {
  const skillPath = path.join(SKILLS_DIR, skillDir, 'SKILL.md');
  if (!fs.existsSync(skillPath)) return null;
  
  let content = fs.readFileSync(skillPath, 'utf-8');
  
  // Strip YAML frontmatter
  content = content.replace(/^---[\s\S]*?---\n*/m, '');
  
  // Truncate if too long
  if (content.length > MAX_CHARS_PER_SKILL) {
    content = content.slice(0, MAX_CHARS_PER_SKILL) + '\n[...truncated]';
  }
  
  return content.trim();
}

function main() {
  console.log('Compiling skills from', SKILLS_DIR);
  
  // Collect all unique skill directories
  const allSkillDirs = new Set();
  for (const dirs of Object.values(DOMAIN_SKILL_MAP)) {
    for (const d of dirs) allSkillDirs.add(d);
  }
  
  // Load each skill file
  const skillContents = {};
  let loaded = 0;
  let totalChars = 0;
  
  for (const dir of allSkillDirs) {
    const content = loadSkill(dir);
    if (content) {
      skillContents[dir] = content;
      loaded++;
      totalChars += content.length;
      console.log(`  ✓ ${dir} (${content.length} chars)`);
    } else {
      console.log(`  ✗ ${dir} (not found)`);
    }
  }
  
  // Generate TypeScript
  let ts = `/**
 * Auto-generated by scripts/compile-skills.js
 * DO NOT EDIT — regenerate with: node scripts/compile-skills.js
 * 
 * Contains ${loaded} skill files compiled from .agents/skills/
 * Total: ${totalChars} chars
 * Generated: ${new Date().toISOString()}
 */

export const COMPILED_SKILLS: Record<string, string> = {\n`;

  for (const [dir, content] of Object.entries(skillContents)) {
    // Escape backticks and template literals in content
    const escaped = content.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
    ts += `  '${dir}': \`${escaped}\`,\n\n`;
  }
  
  ts += `};\n\n`;
  
  // Export domain mapping
  ts += `export const DOMAIN_TO_SKILLS: Record<string, string[]> = ${JSON.stringify(DOMAIN_SKILL_MAP, null, 2)};\n\n`;
  
  // Export loader function
  ts += `/**
 * Get compiled skill knowledge for a list of domain names.
 * Returns concatenated skill content relevant to the detected domains.
 * Budget: max 12000 chars total to fit in system prompt.
 */
export function getCompiledSkillsForDomains(domains: string[], maxChars: number = 12000): string {
  const seen = new Set<string>();
  const parts: string[] = [];
  let totalLen = 0;

  for (const domain of domains) {
    const skillDirs = DOMAIN_TO_SKILLS[domain] || [];
    for (const dir of skillDirs) {
      if (seen.has(dir)) continue;
      seen.add(dir);
      const content = COMPILED_SKILLS[dir];
      if (!content) continue;
      if (totalLen + content.length > maxChars) break;
      parts.push(\`[SKILL: \${dir}]\\n\${content}\\n[/SKILL]\`);
      totalLen += content.length;
    }
    if (totalLen >= maxChars) break;
  }

  return parts.join('\\n\\n');
}\n`;

  fs.writeFileSync(OUTPUT_FILE, ts, 'utf-8');
  console.log(`\nWrote ${OUTPUT_FILE} (${loaded} skills, ${totalChars} chars)`);
}

main();
